import { useEffect, useState } from "react";
import api, { mensajeError } from "../services/api.js";

const ROLES = ["BODEGA", "ADMINISTRADOR", "CONTABILIDAD"];
const vacio = { nombre: "", correo: "", rol: "BODEGA", codigo_pin: "", password: "" };
function usuarioMap(u) { return { ...u, id: u.ID_USUARIO ?? u.id_usuario, nombre: u.NOMBRE ?? u.nombre, correo: u.CORREO ?? u.correo, rol: u.ROL ?? u.rol, codigo_pin: u.CODIGO_PIN ?? u.codigo_pin, estado: u.ESTADO ?? u.estado }; }

export default function Usuarios() {
  const [usuarios, setUsuarios] = useState([]); const [form, setForm] = useState(null); const [error, setError] = useState("");
  async function cargar() { const { data } = await api.get("/auth/usuarios"); setUsuarios((data.usuarios || []).map(usuarioMap)); }
  useEffect(() => { cargar().catch((e) => setError(mensajeError(e))); }, []);
  async function guardar(e) { e.preventDefault(); setError(""); try { const payload = { ...form }; if (!payload.password) delete payload.password; if (form.id) await api.put(`/auth/usuarios/${form.id}`, payload); else await api.post("/auth/usuarios", payload); setForm(null); cargar(); } catch (err) { setError(mensajeError(err)); } }
  async function cambiarEstado(u) { try { await api.patch(`/auth/usuarios/${u.id}/estado`, { estado: u.estado === "ACTIVO" ? "INACTIVO" : "ACTIVO" }); cargar(); } catch (err) { setError(mensajeError(err)); } }
  return <div className="mx-auto max-w-6xl px-4 py-6"><div className="flex items-center justify-between"><div><h1 className="text-2xl font-semibold">Usuarios</h1><p className="text-sm text-graphite-500">Administra accesos y roles del sistema.</p></div><button onClick={() => setForm(vacio)} className="min-h-touch rounded-lg bg-amber-500 px-4 font-semibold">Crear usuario</button></div>{error && <p className="mt-3 text-sm text-rust-600">{error}</p>}<div className="mt-5 overflow-x-auto rounded-lg border border-graphite-200 bg-white"><table className="w-full text-left text-sm"><thead className="bg-paper-100"><tr><th className="p-3">Nombre</th><th className="p-3">Correo</th><th className="p-3">Rol</th><th className="p-3">PIN</th><th className="p-3">Estado</th><th className="p-3">Acciones</th></tr></thead><tbody>{usuarios.map((u) => <tr key={u.id} className="border-t border-graphite-200"><td className="p-3">{u.nombre}</td><td className="p-3">{u.correo || "—"}</td><td className="p-3">{u.rol}</td><td className="p-3">{u.codigo_pin}</td><td className="p-3">{u.estado}</td><td className="p-3 whitespace-nowrap"><button onClick={() => setForm({ ...u, password: "" })} className="mr-3 text-sky-600">Editar</button><button onClick={() => cambiarEstado(u)} className="text-rust-600">{u.estado === "ACTIVO" ? "Desactivar" : "Activar"}</button></td></tr>)}</tbody></table></div>{form && <div className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4"><form onSubmit={guardar} className="w-full max-w-lg rounded-xl bg-white p-5"><h2 className="text-xl font-semibold">{form.id ? "Editar usuario" : "Crear usuario"}</h2><div className="mt-4 grid gap-3">{[["nombre", "Nombre"], ["correo", "Correo", "email"], ["codigo_pin", "PIN", "text"], ["password", "Contraseña", "password"]].map(([campo, etiqueta, tipo = "text"]) => <label key={campo} className="text-sm font-medium">{etiqueta}<input required={campo !== "correo" && !(form.id && campo === "password")} type={tipo} value={form[campo] || ""} onChange={(e) => setForm({ ...form, [campo]: e.target.value })} className="mt-1 min-h-touch w-full rounded-lg border border-graphite-200 px-3" /></label>)}<label className="text-sm font-medium">Rol<select value={form.rol} onChange={(e) => setForm({ ...form, rol: e.target.value })} className="mt-1 min-h-touch w-full rounded-lg border border-graphite-200 px-3">{ROLES.map((r) => <option key={r}>{r}</option>)}</select></label></div><div className="mt-5 flex justify-end gap-3"><button type="button" onClick={() => setForm(null)} className="min-h-touch px-3">Cancelar</button><button className="min-h-touch rounded-lg bg-amber-500 px-4 font-semibold">Guardar</button></div></form></div>}</div>;
}
